[package]
name = "oc-case-opener"
version = "0.1.0"
description = "A CS2-case-inspired roulette for randomly deciding OC traits"
edition = "2021"

[lib]
name = "oc_case_opener_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
rand = "0.8"

[profile.release]
panic = "abort"
codegen-units = 1
lto = true
opt-level = "s"
